export let cityList = [
    "New York",
    "Los Angeles",
    "Chicago",
    "Houston",
    "Dakar",
    "Phoenix",
    "Toronto",
    "Vancouver",
    "Montreal",
    "Calgary",
    "Ottawa",
    "Guadalajara",
    "Monterrey",
    "Tijuana",
    "São Paulo",
    "Rio de Janeiro",
    "Buenos Aires",
    "Lima",
    "Bogota",
    "Santiago",
    "Caracas",
    "Quito",
    "La Paz",
    "Montevideo",
    "London",
    "Paris",
    "Berlin",
    "Madrid",
    "Rome",
    "Amsterdam",
    "Brussels",
    "Vienna",
    "Copenhagen",
    "Stockholm",
    "Oslo",
    "Dublin",
    "Lisbon",
    "Warsaw",
    "Prague",
    "Zurich",
    "Athens",
    "Budapest",
    "Milan",
    "Munich",
    "Tokyo",
    "Osaka",
    "Seoul",
    "Beijing",
    "Shanghai",
    "Bangkok",
    "Singapore",
    "Kuala Lumpur",
    "Jakarta",
    "Manila",
    "Mumbai",
    "Delhi",
    "Bangalore",
    "Chennai",
    "Islamabad",
    "Karachi",
    "Kathmandu",
    "Hanoi",
    "Ho Chi Minh City",
    "Dhaka",
    "Dubai",
    "Abu Dhabi",
    "Riyadh",
    "Jeddah",
    "Tehran",
    "Istanbul",
    "Jerusalem",
    "Amman",
    "Baghdad",
    "Doha",
    "Cairo",
    "Lagos",
    "Nairobi",
    "Johannesburg",
    "Cape Town",
    "Casablanca",
    "Accra",
    "Addis Ababa",
    "Algiers",
    "Tunis",
    "Sydney",
    "Melbourne",
    "Brisbane",
    "Perth",
    "Adelaide",
    "Auckland",
    "Wellington",
    "Christchurch",
    "Suva",
    "Port Moresby",
  ];
  